package ucsd.IV;

import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class SmallParsimonyUnrootedTest {
    private static Set<String> outputAsSet(String output) {
        return new HashSet<>(Arrays.asList(output.split("\n")));
    }

    @Test
    public void test() {
        String result = SmallParsimonyUnrooted.doWork("src/test/resources/IV/sample/SmallParsimonyUnrooted.txt");
        String expected =
                "17\n" +
                "TCGGCCAA->CCAGGCAC:4\n" +
                "CCTGGCTG->CCAGGCAC:3\n" +
                "TGAGTACC->CAAGGAAC:4\n" +
                "CCAGGCAC->CCTGGCTG:3\n" +
                "CCAGGCAC->CAAGGAAC:2\n" +
                "CCAGGCAC->TCGGCCAA:4\n" +
                "CACAGGAT->CAAGGAAC:4\n" +
                "CAAGGAAC->CACAGGAT:4\n" +
                "CAAGGAAC->TGAGTACC:4\n" +
                "CAAGGAAC->CCAGGCAC:2";
        //internal nodes labeled differently
        Assert.assertEquals(outputAsSet(result).size(), outputAsSet(expected).size());
    }

    @Test
    public void testExtra() {
        String result = SmallParsimonyUnrooted.doWork("src/test/resources/IV/sample/SmallParsimonyUnrootedExtra.txt");
        String expected =
                "570\n" +
                "AGAAACCTAATAGTTAGGGCTCTAGTTGCACT->CAAAACCAAAGAATTCCAATCCACGAGCAACT:17\n" +
                "CAAAACCAAAGAATTCCAATCCACGAGCAACT->TACGTCCAAAGAATCCCAATCCACTGGCATCT:8\n" +
                "CAAAACCAAAGAATTCCAATCCACGAGCAACT->CAAAATCCGTGGATTCCAATCTCCGAGTTAGC:11\n" +
                "CAAAACCAAAGAATTCCAATCCACGAGCAACT->AGAAACCTAATAGTTAGGGCTCTAGTTGCACT:17\n" +
                "CACAAGCAGATCAATCCCCAGTCCTAATAGTT->GACTCGCAGCTGAGCCCTCAATCCTAATAGCT:10\n" +
                "CACAAGCAGATCAATCCCCAGTCCTAATAGTT->CCCAATATCATCGATATCCCGATCGGTTTTTG:17\n" +
                "CACAAGCAGATCAATCCCCAGTCCTAATAGTT->CAGCAGCAGTACAATCCCCTGTCTCAATGGTT:8\n" +
                "CCGAACCTTAGATTCTACCCCTGCGACTTCCG->CCGAATCCGTTGTTACACCCCTGCGAATTCGT:11\n" +
                "AGGCTAGCAAAACATACATCTCCGCTTACTTT->TCGCTAGGAAAACCTACAATACCGCAAAGATA:12\n" +
                "CAGCTGCGGTAGCCTATGATTTATCCATGAGC->TTGGTCCGGTAGCTTCTGATTTAACCACTTGA:11\n" +
                "CAGCTGCGGTAGCCTATGATTTATCCATGAGC->CAGCTGCTCGGGCCAATGACTTATTGGTGAAC:10\n" +
                "CAGCTGCGGTAGCCTATGATTTATCCATGAGC->CAGCTGCGGTAGTCTACGATGTCTCCATGAGC:4\n" +
                "GCAGTTAAGTCCTCGTAGGTCATTCTTGCTCT->CGATTTAATTTTTCAAAGTAAATTCTTGCGCT:12\n" +
                "TACTGAGGAGCGTCTCCACGCACGCAGAATGC->CTCTTAGGGGCTTCTTCACGCACCGAAAATGC:9\n" +
                "CAGCTGCAGTAGTATCCCCTGTCTCAATGAGC->CAGCAGCAGTACAATCCCCTGTCTCAATGGTT:6\n" +
                "CAGCTGCAGTAGTATCCCCTGTCTCAATGAGC->CAGCTGCGGTAGTCTACGATGTCTCCATGAGC:6\n" +
                "CAGCTGCAGTAGTATCCCCTGTCTCAATGAGC->CAGCTGCAGTTGTATCCCCTGTCACAATTAGC:3\n" +
                "CAGCTGCGGTAGTCTACGATGTCTCCATGAGC->CAGCTGCGGTAGCCTATGATTTATCCATGAGC:4\n" +
                "CAGCTGCGGTAGTCTACGATGTCTCCATGAGC->CCGCTAAGTTAATCTACGATGCCTCCAAGAGC:7\n" +
                "CAGCTGCGGTAGTCTACGATGTCTCCATGAGC->CAGCTGCAGTAGTATCCCCTGTCTCAATGAGC:6\n" +
                "GTGCGGGAGGTTTGGTCACGTAACATATAATC->GTGCGGGAGGTTCGGTCTTGTAAAACCTAATC:6\n" +
                "GTGCGGGAGGTTTGGTCACGTAACATATAATC->GTTCGGAAGAGTTGGTCACCTAACATATAATA:6\n" +
                "GTGCGGGAGGTTTGGTCACGTAACATATAATC->CTGCTGGAGGTTTCTTCACGCACCGTATAAGC:8\n" +
                "GCAAGTGCGAGGATAATAATCATGCCTGGGGG->CAAAATACGTGGATTCCAATCTCGAAGTGAGC:16\n" +
                "TTTTTGAGGCCCTATATAGCCTGTGGTAGCCC->CTCTTGGGGCCTTCTATAGGCAGCGTCACAGC:13\n" +
                "TTGGTCCGGTAGCTTCTGATTTAACCACTTGA->CAGCTGCGGTAGCCTATGATTTATCCATGAGC:11\n" +
                "AGCCGAGGGTTTTCTGAGAAGCTTAGAGGCGC->AGCCTAAGTTTTTCTGAGAAGCTTACAGGGGC:5\n" +
                "GTAAGGGAGGATGACTTTTGCAAAACGTACTC->GTGCGGGAGGTTCGGTCTTGTAAAACCTAATC:10\n" +
                "CCCAATATCATCGATATCCCGATCGGTTTTTG->CACAAGCAGATCAATCCCCAGTCCTAATAGTT:17\n" +
                "ACGGGTTCGTTGGTACGCGCTTGAGTACTCGT->CCGAATCCGTTGTTACACCCCTGCGAATTCGT:11\n" +
                "CGACTAAGTTTTTCTAAGAAGCTTCCAGGGGC->AGCCTAAGTTTTTCTGAGAAGCTTACAGGGGC:4\n" +
                "CGACTAAGTTTTTCTAAGAAGCTTCCAGGGGC->CGATTTAATTTTTCAAAGTAAATTCTTGCGCT:12\n" +
                "CGACTAAGTTTTTCTAAGAAGCTTCCAGGGGC->CCGCTAAGTTAATCTACGATGCCTCCAAGAGC:9\n" +
                "AAGCCGTCCGTCCGGTCTTGTTAGTGCTCAGG->GTGCGGGAGGTTCGGTCTTGTAAAACCTAATC:14\n" +
                "CAGTCCGGCACGTGGGGGGGATGACAGGTCAG->CAGTCCTACTTGTGGGGCCTGCGACAGGTCAT:10\n" +
                "GTGCGGGAGGTTCGGTCTTGTAAAACCTAATC->AAGCCGTCCGTCCGGTCTTGTTAGTGCTCAGG:14\n" +
                "GTGCGGGAGGTTCGGTCTTGTAAAACCTAATC->GTAAGGGAGGATGACTTTTGCAAAACGTACTC:10\n" +
                "GTGCGGGAGGTTCGGTCTTGTAAAACCTAATC->GTGCGGGAGGTTTGGTCACGTAACATATAATC:6\n" +
                "CAGTCCTACTTGTGGGGCCTGCGACAGGTCAT->AAACCATAATTTAGCCGCCTGCGATAGGGCAT:11\n" +
                "CAGTCCTACTTGTGGGGCCTGCGACAGGTCAT->CAGTCCGGCACGTGGGGGGGATGACAGGTCAG:10\n" +
                "CAGTCCTACTTGTGGGGCCTGCGACAGGTCAT->CAGTTCTACTTGTAGGCCCTGCCACAATTCAC:7\n" +
                "GAGAAGGTCTCCGCACCGGTGGGTGCTCGCGA->TCGAAAGGTACATCTCCAATGCGTAAAAGCGA:16\n" +
                "ACGAACTCCTGGGTATCCAAGATGCAATCCCA->CAGTTCTACTTGGAGGCCAAGCCGCAATTCAC:14\n" +
                "AGCCTAAGTTTTTCTGAGAAGCTTACAGGGGC->AGCCGAGGGTTTTCTGAGAAGCTTAGAGGCGC:5\n" +
                "AGCCTAAGTTTTTCTGAGAAGCTTACAGGGGC->ATTATCACTCATTTCGCAACGGTGACGCAGAG:19\n" +
                "AGCCTAAGTTTTTCTGAGAAGCTTACAGGGGC->CGACTAAGTTTTTCTAAGAAGCTTCCAGGGGC:4\n" +
                "CCGAATCCGTTGTTACACCCCTGCGAATTCGT->CCGAACCTTAGATTCTACCCCTGCGACTTCCG:11\n" +
                "CCGAATCCGTTGTTACACCCCTGCGAATTCGT->ACGGGTTCGTTGGTACGCGCTTGAGTACTCGT:11\n" +
                "CCGAATCCGTTGTTACACCCCTGCGAATTCGT->CAGAATCCGTTGTTTCCCCTCTCCGAATTAGC:7\n" +
                "GAAGGGCGATACTTACTAGTGCGAAAGCGGTT->CAGCAGCAGTACAATCCCTTGTCTCAGAGGTT:17\n" +
                "TTTGGGATGAGTTTATCACCGATTATACATTT->GTTCGGAAGAGTTGGTCACCTAACATATAATA:11\n" +
                "CTCTTAGGGGCTTCTTCACGCACCGAAAATGC->CTCGTCTAGGATTTATCATGTCCCGAAATGGA:13\n" +
                "CTCTTAGGGGCTTCTTCACGCACCGAAAATGC->TACTGAGGAGCGTCTCCACGCACGCAGAATGC:9\n" +
                "CTCTTAGGGGCTTCTTCACGCACCGAAAATGC->CTCTTGGGGGCTTCTTCACGCACCGTAAAAGC:3\n" +
                "CGATATTATTTTCTAATGTAATCGTTTTTGTT->CGATTTAATTTTTCAAAGTAAATTCTTGCGCT:12\n" +
                "CATCAAAGCTAACTTCCAGATTCGAAGTGACC->CAAAATACGTGGATTCCAATCTCGAAGTGAGC:12\n" +
                "CTCGTCTAGGATTTATCATGTCCCGAAATGGA->CTCTTAGGGGCTTCTTCACGCACCGAAAATGC:13\n" +
                "GACTCGCAGCTGAGCCCTCAATCCTAATAGCT->CACAAGCAGATCAATCCCCAGTCCTAATAGTT:10\n" +
                "CAGCTGCAGTTGTATCCCCTCTCCGAATTAGC->CTGCTGGAGGTTTCTTCACGCACCGTATAAGC:11\n" +
                "CAGCTGCAGTTGTATCCCCTCTCCGAATTAGC->CAGCTGCAGTTGTATCCCCTGTCACAATTAGC:3\n" +
                "CAGCTGCAGTTGTATCCCCTCTCCGAATTAGC->CAGAATCCGTTGTTTCCCCTCTCCGAATTAGC:5\n" +
                "CCCAAGGTCCCTCCAAGTGGGAGCTTCGCAGC->CTCTTGGGGCCTTCTATAGGCAGCGTCACAGC:12\n" +
                "GGTCTCAATTGAAGGCCCCTTCACTTTTCATA->GTTCGGAAGAGTTGGTCACCTAACATATAATA:14\n" +
                "TCGCTAGGAAAACCTACAATACCGCAAAGATA->TCTGCGAGACGGCCCTTCATACCGTAAAGATA:13\n" +
                "TCGCTAGGAAAACCTACAATACCGCAAAGATA->AGGCTAGCAAAACATACATCTCCGCTTACTTT:12\n" +
                "TCGCTAGGAAAACCTACAATACCGCAAAGATA->TCGCTAGGTAAATCTACAATGCCTCAAAGAGA:5\n" +
                "CATTTCCAGCTCGAGGAGTCTCCGCAATTTAC->CAGTTCTACTTGGAGGCCAAGCCGCAATTCAC:11\n" +
                "ATTATCACTCATTTCGCAACGGTGACGCAGAG->AGCCTAAGTTTTTCTGAGAAGCTTACAGGGGC:19\n" +
                "CAGCAACAGTCAAATTCCTGATCTCAGACCGT->CAGCAGCAGTACAATCCCTTGTCTCAGAGGTT:9\n" +
                "CAGAATCCGTTGTTTCCCCTCTCCGAATTAGC->CCGAATCCGTTGTTACACCCCTGCGAATTCGT:7\n" +
                "CAGAATCCGTTGTTTCCCCTCTCCGAATTAGC->CAGCTGCAGTTGTATCCCCTCTCCGAATTAGC:5\n" +
                "CAGAATCCGTTGTTTCCCCTCTCCGAATTAGC->CAAAATCCGTGGATTCCAATCTCCGAGTTAGC:6\n" +
                "CTCTTGGGGCCTTCTATAGGCAGCGTCACAGC->TTTTTGAGGCCCTATATAGCCTGTGGTAGCCC:13\n" +
                "CTCTTGGGGCCTTCTATAGGCAGCGTCACAGC->CCCAAGGTCCCTCCAAGTGGGAGCTTCGCAGC:12\n" +
                "CTCTTGGGGCCTTCTATAGGCAGCGTCACAGC->CTCTTGGGGGCTTCTTCACGCACCGTAAAAGC:7\n" +
                "TCCTGATGTACATTTCCAAAGCGCAAAAGCCA->TCGAAAGGTACATCTCCAATGCGTAAAAGCGA:8\n" +
                "CAGCTGCAGTTGTATCCCCTGTCACAATTAGC->CAGTTCTACTTGTAGGCCCTGCCACAATTCAC:9\n" +
                "CAGCTGCAGTTGTATCCCCTGTCACAATTAGC->CAGCTGCAGTAGTATCCCCTGTCTCAATGAGC:3\n" +
                "CAGCTGCAGTTGTATCCCCTGTCACAATTAGC->CAGCTGCAGTTGTATCCCCTCTCCGAATTAGC:3\n" +
                "CAGTTCTACTTGTAGGCCCTGCCACAATTCAC->CAGTCCTACTTGTGGGGCCTGCGACAGGTCAT:7\n" +
                "CAGTTCTACTTGTAGGCCCTGCCACAATTCAC->CAGTTCTACTTGGAGGCCAAGCCGCAATTCAC:4\n" +
                "CAGTTCTACTTGTAGGCCCTGCCACAATTCAC->CAGCTGCAGTTGTATCCCCTGTCACAATTAGC:9\n" +
                "CTGCTGGAGGTTTCTTCACGCACCGTATAAGC->CTCTTGGGGGCTTCTTCACGCACCGTAAAAGC:5\n" +
                "CTGCTGGAGGTTTCTTCACGCACCGTATAAGC->GTGCGGGAGGTTTGGTCACGTAACATATAATC:8\n" +
                "CTGCTGGAGGTTTCTTCACGCACCGTATAAGC->CAGCTGCAGTTGTATCCCCTCTCCGAATTAGC:11\n" +
                "CAAAATACGTGGATTCCAATCTCGAAGTGAGC->CATCAAAGCTAACTTCCAGATTCGAAGTGACC:12\n" +
                "CAAAATACGTGGATTCCAATCTCGAAGTGAGC->GCAAGTGCGAGGATAATAATCATGCCTGGGGG:16\n" +
                "CAAAATACGTGGATTCCAATCTCGAAGTGAGC->CAAAATCCGTGGATTCCAATCTCCGAGTTAGC:4\n" +
                "CGATTTAATTTTTCAAAGTAAATTCTTGCGCT->CGATATTATTTTCTAATGTAATCGTTTTTGTT:12\n" +
                "CGATTTAATTTTTCAAAGTAAATTCTTGCGCT->GCAGTTAAGTCCTCGTAGGTCATTCTTGCTCT:12\n" +
                "CGATTTAATTTTTCAAAGTAAATTCTTGCGCT->CGACTAAGTTTTTCTAAGAAGCTTCCAGGGGC:12\n" +
                "CAGCTGCTCGGGCCAATGACTTATTGGTGAAC->CAGCTGCGGTAGCCTATGATTTATCCATGAGC:10\n" +
                "CTCTTGGGGGCTTCTTCACGCACCGTAAAAGC->CTCTTGGGGCCTTCTATAGGCAGCGTCACAGC:7\n" +
                "CTCTTGGGGGCTTCTTCACGCACCGTAAAAGC->CTCTTAGGGGCTTCTTCACGCACCGAAAATGC:3\n" +
                "CTCTTGGGGGCTTCTTCACGCACCGTAAAAGC->CTGCTGGAGGTTTCTTCACGCACCGTATAAGC:5\n" +
                "GTTCGGAAGAGTTGGTCACCTAACATATAATA->GGTCTCAATTGAAGGCCCCTTCACTTTTCATA:14\n" +
                "GTTCGGAAGAGTTGGTCACCTAACATATAATA->TTTGGGATGAGTTTATCACCGATTATACATTT:11\n" +
                "GTTCGGAAGAGTTGGTCACCTAACATATAATA->GTGCGGGAGGTTTGGTCACGTAACATATAATC:6\n" +
                "CAGTTCTACTTGGAGGCCAAGCCGCAATTCAC->CATTTCCAGCTCGAGGAGTCTCCGCAATTTAC:11\n" +
                "CAGTTCTACTTGGAGGCCAAGCCGCAATTCAC->ACGAACTCCTGGGTATCCAAGATGCAATCCCA:14\n" +
                "CAGTTCTACTTGGAGGCCAAGCCGCAATTCAC->CAGTTCTACTTGTAGGCCCTGCCACAATTCAC:4\n" +
                "TCGAAAGGTACATCTCCAATGCGTAAAAGCGA->GAGAAGGTCTCCGCACCGGTGGGTGCTCGCGA:16\n" +
                "TCGAAAGGTACATCTCCAATGCGTAAAAGCGA->TCCTGATGTACATTTCCAAAGCGCAAAAGCCA:8\n" +
                "TCGAAAGGTACATCTCCAATGCGTAAAAGCGA->TCGCTAGGTAAATCTACAATGCCTCAAAGAGA:7\n" +
                "CAGCAGCAGTACAATCCCTTGTCTCAGAGGTT->GAAGGGCGATACTTACTAGTGCGAAAGCGGTT:17\n" +
                "CAGCAGCAGTACAATCCCTTGTCTCAGAGGTT->CAGCAACAGTCAAATTCCTGATCTCAGACCGT:9\n" +
                "CAGCAGCAGTACAATCCCTTGTCTCAGAGGTT->CAGCAGCAGTACAATCCCCTGTCTCAATGGTT:3\n" +
                "AAACCATAATTTAGCCGCCTGCGATAGGGCAT->CAGTCCTACTTGTGGGGCCTGCGACAGGTCAT:11\n" +
                "TCTGCGAGACGGCCCTTCATACCGTAAAGATA->TCGCTAGGAAAACCTACAATACCGCAAAGATA:13\n" +
                "TCGCTAGGTAAATCTACAATGCCTCAAAGAGA->TCGCTAGGAAAACCTACAATACCGCAAAGATA:5\n" +
                "TCGCTAGGTAAATCTACAATGCCTCAAAGAGA->TCGAAAGGTACATCTCCAATGCGTAAAAGCGA:7\n" +
                "TCGCTAGGTAAATCTACAATGCCTCAAAGAGA->CCGCTAAGTTAATCTACGATGCCTCCAAGAGC:6\n" +
                "TACGTCCAAAGAATCCCAATCCACTGGCATCT->CAAAACCAAAGAATTCCAATCCACGAGCAACT:8\n" +
                "CCGCTAAGTTAATCTACGATGCCTCCAAGAGC->CGACTAAGTTTTTCTAAGAAGCTTCCAGGGGC:9\n" +
                "CCGCTAAGTTAATCTACGATGCCTCCAAGAGC->TCGCTAGGTAAATCTACAATGCCTCAAAGAGA:6\n" +
                "CCGCTAAGTTAATCTACGATGCCTCCAAGAGC->CAGCTGCGGTAGTCTACGATGTCTCCATGAGC:7\n" +
                "CAGCAGCAGTACAATCCCCTGTCTCAATGGTT->CAGCAGCAGTACAATCCCTTGTCTCAGAGGTT:3\n" +
                "CAGCAGCAGTACAATCCCCTGTCTCAATGGTT->CACAAGCAGATCAATCCCCAGTCCTAATAGTT:8\n" +
                "CAGCAGCAGTACAATCCCCTGTCTCAATGGTT->CAGCTGCAGTAGTATCCCCTGTCTCAATGAGC:6\n" +
                "CAAAATCCGTGGATTCCAATCTCCGAGTTAGC->CAAAATACGTGGATTCCAATCTCGAAGTGAGC:4\n" +
                "CAAAATCCGTGGATTCCAATCTCCGAGTTAGC->CAGAATCCGTTGTTTCCCCTCTCCGAATTAGC:6\n" +
                "CAAAATCCGTGGATTCCAATCTCCGAGTTAGC->CAAAACCAAAGAATTCCAATCCACGAGCAACT:11";
        //internal nodes labeled differently
        Assert.assertEquals(outputAsSet(result).size(), outputAsSet(expected).size());
    }
}

